//! Trait for chaining tuples together.
//!
//! The `ChainTuple` trait allows concatenating two tuples into a single tuple.
//! This is primarily used internally to simplify type definitions in the
//! `TypedTuple` trait implementations.

/// Trait for chaining two tuples together.
///
/// This trait is implemented for all combinations of tuple sizes (up to 64
/// elements by default, or 128 with the `len_128` feature). It enables
/// type-level tuple concatenation.
///
/// # Type Parameters
///
/// * `Other` - The tuple type to append to `Self`
///
/// # Examples
///
/// ```rust
/// # use typed_tuple::ChainTuple;
/// // Type aliases to demonstrate chaining
/// type Left = (u8, u16);
/// type Right = (u32, u64);
/// type Chained = <Left as ChainTuple<Right>>::Output;
///
/// // Chained is equivalent to (u8, u16, u32, u64)
/// let _: Chained = (1u8, 2u16, 3u32, 4u64);
/// ```
pub trait ChainTuple<Other> {
    /// The resulting tuple type after chaining `Self` with `Other`.
    type Output;
}

// The implementations are generated by the proc macro
typed_tuple_macros::generate_chain_tuple_impls!();
